### ISSUE TITLE
注解了ignore=true，空指针异常

### ISSUE THREAD

**Issue by x492016665** [houbb/data-factory#4]
@Override
    protected Object buildDataValue(DataFactory dataFactory, IContext context,
                               Class<?> tClass) {
        // 忽略字段，直接返回 null
        if (dataFactory.ignore()) {
            return null;
        }
dataFatory 是null 此处是否需要判断 if(dataFatory == null || dataFactory.ignore() ) {return null;}

**Comment by houbb** [comment]
感谢提醒，有时间我确认下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: x492016665 ***@***.***&gt;
发送时间: 2021年11月30日 11:24
收件人: houbb/data-factory ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/data-factory] 注解了ignore=true，空指针异常 (Issue #4)





 
@OverRide
 protected Object buildDataValue(DataFactory dataFactory, IContext context,
 Class<?&gt; tClass) {
 // 忽略字段，直接返回 null
 if (dataFactory.ignore()) {
 return null;
 }
 dataFatory 是null 此处是否需要判断 if(dataFatory == null || dataFactory.ignore() ) {return null;}
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by houbb** [comment]
V1.2.0 已修复。
